VPC Endpoint policy updates
aws-samples/data-perimeter-policy-examples pull request #18
Opened 2024-02-04 05:08 UTC by shayfisher

add ec2 endpoint policy which allows marketplace consumption and amazon images consumption
add s3 actual AL2023 location - the current location doesn't necessary is a name of a bucket
add Start* to SSM - to allow actions such as port forwarding via SSM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-05 19:10 UTC, shayfisher commented
@liwadman Can you please review my PR?

2024-02-05 19:34 UTC, SwaraGandhi commented
> @liwadman Can you please review my PR?

Hi @shayfisher,

Thank you for submitting the PR!
I will update the repo with the above recommendation once our internal review process is complete.

2024-02-18 06:42 UTC, shayfisher commented
Hi @SwaraGandhi ,
Are there any news about the review process ?
Thank you!

2024-02-21 19:37 UTC, SwaraGandhi requested changes

2024-02-21 19:37 UTC, SwaraGandhi commented on vpc_endpoint_policies/ec2_endpoint_policy copy.json
Hi @shayfisher,

Line 46 : Can you please remove "aws-marketplace", > We would not want to add it here because of the concerns outlined in this blog.

Line 47 : Remove  "<AMI-building-account-id>" as it will be already covered by the first statement.

2024-02-21 19:39 UTC, SwaraGandhi commented on vpc_endpoint_policies/s3_endpoint_policy.json
Can you also please add this bucket name to the vpc_endpoint_policies/README.md file under "AWS owned bucket for Kernel Live Patching on Amazon Linux 2023".

2024-02-22 09:50 UTC, shayfisher commented on vpc_endpoint_policies/s3_endpoint_policy.json
Hi @SwaraGandhi ,
Just pushed the updates

2024-02-27 17:37 UTC, SwaraGandhi commented on vpc_endpoint_policies/s3_endpoint_policy.json
Hi @shayfisher , 

We will require more time to validate the ssm:Start*. In order to merge the changes that you already have with the EC2 and S3 endpoint policies, can you remove the changes made to the ssm:Start* for now?
Internal review validates access paths for the different ssm actions before adding them to the policies.

2024-02-28 05:08 UTC, shayfisher commented on vpc_endpoint_policies/s3_endpoint_policy.json
Pushed a commit that removed the ssm:Start* action

2024-02-29 01:11 UTC, SwaraGandhi approved these changes

2024-02-29 01:12 UTC, merged

2024-02-29 05:33 UTC, shayfisher commented
Hi @SwaraGandhi ,
Should I open a new PR for ssm:Start* ?